// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AlbumBridge = { id: number | null, song: string | null, album: string | null, };

export type BackgroundConfig = { layers: Array<BackgroundLayer>, opacity: number | null, blur: number | null, grain_opacity: number | null, };

export type BackgroundLayer = LinearLayer | RadialLayer | ConicLayer | ImageLayer;

export type BackgroundLayerBase = { opacity: number | null, blend_mode: string | null, position: string | null, size: string | null, repeat: string | null, };

export type ColorStop = { color: string, pos: number | null, };

export type ConicLayer = { type: LayerType, angle: number | null, at: string | null, stops: Array<ColorStop>, opacity: number | null, blend_mode: string | null, position: string | null, size: string | null, repeat: string | null, };

export type EntityInfo = string;

export type GeneralSettings = { language: string | null, minimizeToTray: boolean | null, launchAtLogin: boolean | null, 
/**
 * Whether to automatically scan on app start.
 */
autoScanEnabled: boolean | null, 
/**
 * Folders to scan. Absolute paths.
 */
scanFolders: Array<string> | null, 
/**
 * Minimal duration rule when scanning.
 */
scanMinDuration: ScanMinDuration | null, 
/**
 * File format rule when scanning.
 */
scanFormats: ScanFormats | null, };

export type GetEntityOptions = { artist: QueryableArtist | null, album: QueryableAlbum | null, genre: QueryableGenre | null, playlist: QueryablePlaylist | null, inclusive: boolean | null, };

export type GetSongOptions = { song: SearchableSong | null, artist: QueryableArtist | null, album: QueryableAlbum | null, genre: QueryableGenre | null, playlist: QueryablePlaylist | null, inclusive: boolean | null, };

export type ImageLayer = { type: LayerType, url: string, opacity: number | null, blend_mode: string | null, position: string | null, size: string | null, repeat: string | null, };

export type LayerType = { "type": "linear" } | { "type": "radial" } | { "type": "conic" } | { "type": "image" };

export type LinearLayer = { type: LayerType, angle: number | null, stops: Array<ColorStop>, opacity: number | null, blend_mode: string | null, position: string | null, size: string | null, repeat: string | null, };

export type LyricsSettings = { playerImplementation: string | '', fontFamily: string | null, fontWeight: string | null, letterSpacing: string | null, sizePreset: string | null, lineBlurEffect: boolean | null, lineScaleEffect: boolean | null, lineSpringAnimation: boolean | null, advanceLineTiming: boolean | null, wordFadeWidth: number | null, translationLine: boolean | null, romanLine: boolean | null, swapTransRomanLine: boolean | null, };

export type PlayerMode = "Sequential" | "Single" | "Shuffle" | "ListLoop";

export type PlayerState = "PLAYING" | "PAUSED" | "STOPPED" | "LOADING";

export type ProviderInstancePref = { key: string, kind: ProviderKind, enabled: boolean, cfg: Record<string, any>, secure_ref: string | null, };

export type ProviderKind = "spotify" | "youtube" | "bilibili";

export type ProviderSelectorArg = { "type": "single", provider: ProviderKind, } | { "type": "all" } | { "type": "many", providers: Array<ProviderKind>, };

export type QueryableAlbum = { album_id: string | null, album_name: string | null, album_artist: string | null, album_coverPath_high: string | null, album_song_count: number, year: string | null, album_coverPath_low: string | null, album_extra_info: EntityInfo | null, };

export type QueryableArtist = { artist_id: string | null, artist_mbid: string | null, artist_name: string | null, artist_coverPath: string | null, artist_song_count: number, artist_extra_info: EntityInfo | null, sanitized_artist_name: string | null, };

export type QueryableGenre = { genre_id: string | null, genre_name: string | null, genre_song_count: number, };

export type QueryablePlaylist = { playlist_id: string | null, playlist_name: string, playlist_coverPath: string | null, playlist_song_count: number, playlist_desc: string | null, playlist_path: string | null, extension: string | null, icon: string | null, library_item: boolean | null, };

export type QueryableSong = { _id: string | null, path: string | null, size: number | null, inode: string | null, deviceno: string | null, title: string | null, date: string | null, year: string | null, lyrics: string | null, releaseType: string | null, bitrate: number | null, codec: string | null, container: string | null, duration: number | null, sampleRate: number | null, hash: string | null, type: SongType, url: string | null, song_coverPath_high: string | null, playbackUrl: string | null, song_coverPath_low: string | null, date_added: bigint | null, provider_extension: string | null, icon: string | null, show_in_library: boolean | null, track_no: number | null, library_item: boolean | null, };

export type RadialLayer = { type: LayerType, shape: string | null, at: string | null, stops: Array<ColorStop>, opacity: number | null, blend_mode: string | null, position: string | null, size: string | null, repeat: string | null, };

/**
 * File format filter for library scanning.
 */
export type ScanFormats = "common" | "all";

/**
 * Minimal duration rule for library scanning.
 */
export type ScanMinDuration = "sec30" | "min2" | "all";

export type SearchResult = { songs: Array<Song>, artists: Array<QueryableArtist>, playlists: Array<QueryablePlaylist>, albums: Array<QueryableAlbum>, genres: Array<QueryableGenre>, };

export type SearchableSong = { _id: string | null, path: string | null, title: string | null, sample_rate: number | null, hash: string | null, type_: SongType | null, url: string | null, playback_url: string | null, provider_extension: string | null, show_in_library: boolean | null, };

export type Song = { album: QueryableAlbum | null, artists: Array<QueryableArtist> | null, genre: Array<QueryableGenre> | null, _id: string | null, path: string | null, size: number | null, inode: string | null, deviceno: string | null, title: string | null, date: string | null, year: string | null, lyrics: string | null, releaseType: string | null, bitrate: number | null, codec: string | null, container: string | null, duration: number | null, sampleRate: number | null, hash: string | null, type: SongType, url: string | null, song_coverPath_high: string | null, playbackUrl: string | null, song_coverPath_low: string | null, date_added: bigint | null, provider_extension: string | null, icon: string | null, show_in_library: boolean | null, track_no: number | null, library_item: boolean | null, };

export type SongType = "LOCAL" | "URL" | "SPOTIFY" | "DASH" | "HLS";

export type ThemeBackground = { app: BackgroundConfig, toolbar: BackgroundConfig | null, };

export type ThemeDetails = { meta: ThemeMeta, tokens: ThemeTokens, background: ThemeBackground, custom_css: string | null, };

export type ThemeMeta = { id: string, name: string, author: string | null, is_dark: boolean | null, version: string | null, };

export type ThemeTokens = { color_bg: string, color_surface: string, color_border: string, color_divider: string, text_primary: string, text_secondary: string, text_tertiary: string, text_disabled: string, accent: string, on_accent: string, state_hover_bg: string, state_pressed_bg: string, state_selected_bg: string, focus_ring: string, shadow_1: string, colors_border: string | null, menu_accent: string | null, };
