// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BackgroundConfig = { layers: Array<BackgroundLayer>, opacity: number | null, blur: number | null, grain_opacity: number | null, };

export type BackgroundLayer = LinearLayer | RadialLayer | ConicLayer | ImageLayer;

export type BackgroundLayerBase = { opacity: number | null, blend_mode: string | null, position: string | null, size: string | null, repeat: string | null, };

export type ColorStop = { color: string, pos: number | null, };

export type ConicLayer = { type: LayerType, angle: number | null, at: string | null, stops: Array<ColorStop>, opacity: number | null, blend_mode: string | null, position: string | null, size: string | null, repeat: string | null, };

export type ImageLayer = { type: LayerType, url: string, opacity: number | null, blend_mode: string | null, position: string | null, size: string | null, repeat: string | null, };

export type LayerType = { "type": "linear" } | { "type": "radial" } | { "type": "conic" } | { "type": "image" };

export type LinearLayer = { type: LayerType, angle: number | null, stops: Array<ColorStop>, opacity: number | null, blend_mode: string | null, position: string | null, size: string | null, repeat: string | null, };

export type ProviderInstancePref = { key: string, kind: ProviderKind, enabled: boolean, cfg: Record<string, any>, secure_ref: string | null, };

export type ProviderKind = "spotify" | "youtube" | "bilibili";

export type ProviderSelectorArg = { "type": "single", provider: ProviderKind, } | { "type": "all" } | { "type": "many", providers: Array<ProviderKind>, };

export type RadialLayer = { type: LayerType, shape: string | null, at: string | null, stops: Array<ColorStop>, opacity: number | null, blend_mode: string | null, position: string | null, size: string | null, repeat: string | null, };

export type ThemeBackground = { app: BackgroundConfig, toolbar: BackgroundConfig | null, };

export type ThemeDetails = { meta: ThemeMeta, tokens: ThemeTokens, background: ThemeBackground, custom_css: string | null, };

export type ThemeMeta = { id: string, name: string, author: string | null, is_dark: boolean | null, version: string | null, };

export type ThemeTokens = { color_bg: string, color_surface: string, color_border: string, color_divider: string, text_primary: string, text_secondary: string, text_tertiary: string, text_disabled: string, accent: string, on_accent: string, state_hover_bg: string, state_pressed_bg: string, state_selected_bg: string, focus_ring: string, shadow_1: string, colors_border: string | null, menu_accent: string | null, };
