[env]
# 给 ts-rs 的导出目录（按你现有配置保留）
TS_RS_EXPORT_DIR = { value = "src/types", relative = true }

[net]
git-fetch-with-cli = true

[source.crates-io]
replace-with = "ustc"

[source.ustc]
registry = "git://mirrors.ustc.edu.cn/crates.io-index"

# ===== 你原来 wasm 的设置，保留 =====
[target.wasm32-unknown-unknown]
rustflags = ['--cfg', 'getrandom_backend="wasm_js"', '--cfg', 'erase_components', '-C', 'debuginfo=0']
